# Configuraci贸n de Base de Datos Oracle
spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_SERVICE_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

# Configuraci贸n AWS
aws:
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  
# Configuraci贸n Oracle Wallet
oracle:
  wallet:
    path: ${ORACLE_WALLET_PATH:./oracle-wallet}
    password: ${ORACLE_WALLET_PASSWORD}

# Configuraci贸n de funciones serverless
functions:
  product:
    url: ${PRODUCT_FUNCTION_URL:http://localhost:8081}
  warehouse:
    url: ${WAREHOUSE_FUNCTION_URL:http://localhost:8082}

# Puerto del servidor
server:
  port: ${SERVER_PORT:8080}
