server:
  port: ${SERVER_PORT:8080}

# Configuración de Oracle Database (local Docker o Cloud)
spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@inventariobd_high}
    username: ${ORACLE_USER:admin}
    password: ${ORACLE_PASSWORD:Inventariobd123!}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

# Configuración de Oracle Wallet
oracle:
  net:
    wallet_location: ${ORACLE_WALLET_LOCATION:./oracle-wallet}
    tns_admin: ${TNS_ADMIN:./oracle-wallet}

# Configuración de funciones serverless
func:
  productBaseUrl: ${FUNC_PRODUCT_BASE_URL:http://localhost:7071/api}
  warehouseBaseUrl: ${FUNC_WAREHOUSE_BASE_URL:http://localhost:7072/api}

# Logging para debugging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.bff: DEBUG
    org.springframework.web: DEBUG
