server:
  port: ${SERVER_PORT:8080}

# Configuración de Oracle Cloud (OCI)
spring:
  datasource:
    url: jdbc:oracle:thin:@inventariobd_high
    username: admin
    password: Inventariobd123!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

# Configuración de Oracle Wallet
oracle:
  net:
    wallet_location: ${ORACLE_WALLET_LOCATION:./oracle-wallet}
    tns_admin: ${TNS_ADMIN:./oracle-wallet}

# Configuración de funciones serverless (para cuando las crees)
func:
  productBaseUrl: ${FUNC_PRODUCT_BASE_URL:http://localhost:8081/function}
  warehouseBaseUrl: ${FUNC_WAREHOUSE_BASE_URL:http://localhost:8082/function}

# Logging para debugging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.bff: DEBUG
    org.springframework.web: DEBUG
